name: 🔨 Scoop Archive Pro
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-2025 
    environment: dev
    steps:
    - name: 'Set up Scoop'
      shell: pwsh
      run: |
        mkdir "D:\00PackageManager\"
        $env:SCOOP='D:\00PackageManager\Scoop'
        [Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser 
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        scoop bucket add versions
        scoop bucket add nirsoft
        scoop bucket add java
        scoop bucket add nonportable
        scoop bucket add ktools https://github.com/kenyon-wong/ktools
        
        echo "$env:SCOOP\shims" >> $env:GITHUB_PATH

    - name: 'Setup Scoop aria2'
      shell: pwsh 
      run: |
        scoop install -k aria2 sudo git 7zip
        scoop config aria2-warning-enabled false
        scoop config aria2-enabled true
        scoop config aria2-retry-wait 4
        scoop config aria2-split 16
        scoop config aria2-max-connection-per-server 16
        scoop config aria2-min-split-size 4M

    - name: 'Install Required Tools'
      shell: pwsh 
      run: |
        scoop install -k innounp dark
        scoop install -k biome jq yq vim curl wget base64 gawk grep sed less touch which cwrsync cacert openssl-lts-light autocorrect fd
        scoop install -k liberica8-full-jdk liberica11-full-jdk liberica17-full-jdk liberica-full-lts-jdk
        scoop install -k gradle maven jenv idea-ultimate jadx
        scoop install -k python nodejs-lts
        scoop install -k nonportable/burp-suite-pro-np@2024.5
        scoop install -k extras/tableplus
        scoop install -k codeql osv-scanner
        scoop install -k extras/sublime-text vscode obsidian xmlnotepad sumatrapdf sourcegit gui-for-clash
        scoop install -k keepassxc openark kubectl sslscan sqlitestudio keepass-plugin-keepassrpc colortool etcd
        scoop install -k dupeGuru dismplusplus renamer everything everything-cli powertoys TrafficMonitor snipaste vncviewer sysinternals
        scoop install -k vcredist2010 vcredist2012 vcredist2013 vcredist2022
        scoop install -k gogo spray zombie fscan pdtm
        scoop install -k anew anki another-redis-desktop-manager apktool blueteamtools burp-suite-pro-np chromedriver chsrc cmake crawlergo dos2unix dotnet-sdk-lts dotnet3-sdk exiftool ffmpeg ffuf fofax foxmail fscapture gcc git-cliff git-lfs go googlechrome gpg hadolint hashcat honeyview imagemagick keepass ksubdomain lefthook make masscode netspy nircmd nodejs-lts-np nuget office-tool-plus onefetch oss-browser pandoc pdfpatcher picgo pixpin rad rufus screentogif sharex shellcheck SpaceSniffer ssh-config sublime-text tableplus yara yarn zotero
        scoop install -k adb firefox goby nodejs openhashtab-np peazip ruby rust rust-msvc rustup-msvc scoop-search UniGetUI wireshark windows-terminal windowsdesktop-runtime-lts
        scoop cache rm *
        scoop cleanup -k *

    - name: 'Show scoop config'
      shell: pwsh
      run: |
        scoop list
        scoop bucket list
        scoop config 
        scoop download windowsdesktop-runtime-lts windows-terminal firefox googlechrome

    - name: Clone GitHub Repositories
      shell: pwsh
      run: |
        git clone --depth 1 'https://github.com/github/vscode-codeql-starter.git' 'D:\00PackageManager\vscode-codeql-starter'
        git clone --depth 1 'https://github.com/github/codeql.git' 'D:\00PackageManager\CodeqlRules'

    - name: 'Downloads Pip Packages'
      shell: pwsh
      run: |
        echo "D:\00PackageManager\Scoop\apps\python\current\Scripts" >> $GITHUB_PATH
        $env:SCOOPpy='D:\00PackageManager\Scoop\apps\python\current\python.exe'
        & $env:SCOOPpy -m pip install --upgrade pip
        & $env:SCOOPpy -m pip -V
        & $env:SCOOPpy -m pip install sqlmap bs4 XlsxWriter tqdm python-libnmap pyDes pipx openpyxl tldextract
        & $env:SCOOPpy -m pip install colorama rncryptor pandas requests pycryptodome beautifulsoup4 chardet
        & $env:SCOOPpy -m pip install subprocess pocsuite qrcode accelerate androguard docx2pdf docx2txt logging colorlog
        & $env:SCOOPpy -m pip install dsinternals flask gradio ldapdomaindump simplejson python-magic python-docx
        & $env:SCOOPpy -m pip install pysocks pycryptodomex pyopenssl pyreadline gitpython PyYAML click retry argparse
        & $env:SCOOPpy -m pip install frida frida-tools
        git clone --depth 1 https://github.com/r0oth3x49/ghauri.git D:\00PackageManager\ghauri
        & $env:SCOOPpy -m pip install -r D:\00PackageManager\ghauri\requirements.txt
        & $env:SCOOPpy -m pip freeze

    - name: 'Compress Scoop Directory'
      shell: pwsh
      run: |
        $env:SCOOP7z='D:\00PackageManager\Scoop\apps\7zip\current\7z.exe'
        & $env:SCOOP7z a -mx9 -t7z 'D:\00PackageManager.7z' 'D:\00PackageManager\*'
        & $env:SCOOP7z l 'D:\00PackageManager.7z'

    - name: 'Upload Compressed Scoop Directory'
      uses: actions/upload-artifact@v4
      with:
        name: Scoop-00PackageManager-Pro
        path: D:\00PackageManager.7z
        retention-days: 3
        compression-level: 0
