name: 🔨 Scoop Archive Base
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest 
    environment: dev
    steps:
    - name: 'Set up Scoop'
      shell: pwsh
      run: |
        mkdir "D:\00PackageManager\"
        $env:SCOOP='D:\00PackageManager\Scoop'
        [Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser 
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        scoop bucket add versions
        scoop bucket add nirsoft
        scoop bucket add java
        scoop bucket add nonportable
        scoop bucket add ktools https://github.com/kenyon-wong/ktools
        
        echo "$env:SCOOP\shims" >> $env:GITHUB_PATH

    - name: 'Setup Scoop aria2'
      shell: pwsh 
      run: |
        scoop install -k aria2 sudo git 7zip
        scoop config aria2-warning-enabled false
        scoop config aria2-enabled true
        scoop config aria2-retry-wait 4
        scoop config aria2-split 16
        scoop config aria2-max-connection-per-server 16
        scoop config aria2-min-split-size 4M
 
    - name: 'Install Required Tools'
      shell: pwsh 
      run: |
        scoop install -k innounp dark
        scoop install -k biome jq yq vim curl wget base64 gawk grep sed less touch which cwrsync cacert openssl-lts-light autocorrect fd sourcegit
        scoop cache rm *
        scoop cleanup -k *
        
    - name: 'Show scoop config'
      shell: pwsh
      run: |
        scoop list
        scoop bucket list
        scoop config

    - name: 'Compress Scoop Directory'
      shell: pwsh
      run: |
        $env:SCOOP7z='D:\00PackageManager\Scoop\apps\7zip\current\7z.exe'
        & $env:SCOOP7z a -mx9 -t7z -snh -snl 'D:\00PackageManager.7z' 'D:\00PackageManager\*'
        & $env:SCOOP7z l 'D:\00PackageManager.7z'

    - name: 'Upload Compressed Scoop Directory'
      uses: actions/upload-artifact@v4
      with:
        name: Scoop-00PackageManager-Base
        path: D:\00PackageManager.7z
        retention-days: 3
        compression-level: 0
